<?php
return [
	"Hotel Icons" => [
		"hotel-ico hotel-icon-01",
		"hotel-ico hotel-icon-02",
		"hotel-ico hotel-icon-03",
		"hotel-ico hotel-icon-04",
		"hotel-ico hotel-icon-05",
		"hotel-ico hotel-icon-06",
		"hotel-ico hotel-icon-07",
		"hotel-ico hotel-icon-09",
		"hotel-ico hotel-icon-08",
		"hotel-ico hotel-icon-10",
		"hotel-ico hotel-icon-11",
		"hotel-ico hotel-icon-12",
		"hotel-ico hotel-icon-13",
		"hotel-ico hotel-icon-14",
		"hotel-ico hotel-icon-16",
		"hotel-ico hotel-icon-15",
		"hotel-ico hotel-icon-17",
		"hotel-ico hotel-icon-18",
		"hotel-ico hotel-icon-19",
		"hotel-ico hotel-icon-20",
		"hotel-ico hotel-icon-33",
		"hotel-ico hotel-icon-32",
		"hotel-ico hotel-icon-31",
		"hotel-ico hotel-icon-30",
		"hotel-ico hotel-icon-29",
		"hotel-ico hotel-icon-28",
		"hotel-ico hotel-icon-27",
		"hotel-ico hotel-icon-26",
		"hotel-ico hotel-icon-25",
		"hotel-ico hotel-icon-24",
		"hotel-ico hotel-icon-23",
		"hotel-ico hotel-icon-22",
		"hotel-ico hotel-icon-21"
	]
];